# Generated by Django 5.0.4 on 2024-04-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Teacher Picture')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('tg_username', models.CharField(max_length=100, verbose_name='telegram username')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('bio', models.TextField(verbose_name='bio')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ('-created',),
            },
        ),
    ]
