# Generated by Django 5.0.4 on 2024-05-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cource', '0002_alter_course_options_course_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='youtube video url'),
        ),
    ]
